[package]
name = "termm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
nix.workspace = true
serde.workspace = true
tauri = { version = "2.11.5" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dev-dependencies]
serde_json.workspace = true

[[bin]]
name = "termm"
path = "src/main.rs"
